version: "2"

services:
  app:
    env_file: env.production
    command: >
      sh -cex "
        cd /video-upload;
        /virtualenv/bin/alembic upgrade head;
        /virtualenv/bin/uwsgi --master --module video_upload:app --processes 5 --enable-threads --chmod-socket=666 --socket /var/run/video_upload/uwsgi.socket;
      "

  worker:
    env_file: env.production

  scheduler:
    env_file: env.production
